source "http://rubygems.org"

gem 'uuid'
gem 'base62'
gem 'colored'
gem 'bson', 	'~>1.9.2'
#gem 'bson_ext'
gem 'require_all'
gem 'json',        '>= 1.7.7'
gem 'net-ssh'
gem 'net-scp'
gem 'mongo'
#gem 'pg'
gem 'jdbc-postgres'
gem 'daemons'
gem 'logger'
gem 'grape'	'~>0.9.0'
gem 'grape-swagger'	'~>0.8.0'
gem 'atomic'
gem 'facter'
gem 'rufus-scheduler'
gem 'warbler'
gem 'puma'
gem 'rubyipmi'

group :test do
  gem 'rspec',              '>= 2.13.0'
  gem 'rspec-mocks',        '>= 2.13.0'
  gem 'rspec-expectations', '>= 2.13.0'
end
