source 'http://rubygems.org'

gem 'uuid'
gem 'base62'
gem 'colored'
gem 'bson'
gem 'bson_ext'
gem 'json'
gem 'net-ssh'
gem 'net-scp'
gem 'mongo', '~>1.12.0'
gem 'jdbc-postgres'
gem 'daemons'
gem 'logger'
gem 'grape'
gem 'grape-swagger'
gem 'facter'
gem 'rufus-scheduler'
gem 'warbler'
gem 'puma'
gem 'rubyipmi'

group :test do
  gem 'rspec'
  gem 'rspec-mocks'
  gem 'rspec-expectations'
end
