#!/usr/bin/env ruby
#
# CLI Control for ProjectHanlon
# Format will be 'project_hanlon [module namespace] [module args{}]'
#

# We first add our Lib path to the load path. This is for non-gem ease of use
require 'pathname'
$LOAD_PATH.unshift((Pathname(__FILE__).realpath.dirname + '../lib').cleanpath.to_s)

require 'rubygems' if RUBY_VERSION < '1.9'
require 'project_hanlon/cli'

exit ProjectHanlon::CLI.new.run(*ARGV)
