#!/usr/bin/env ruby
#
# CLI Control for ProjectHanlon
# Format will be 'project_hanlon [module namespace] [module args{}]'
#

# We first add our Lib path to the load path. This is for non-gem ease of use
require 'pathname'
#$LOAD_PATH.unshift((Pathname(__FILE__).realpath.dirname + '../lib').cleanpath.to_s)

$LOAD_PATH.unshift((Pathname(__FILE__).realpath.dirname + '../core').cleanpath.to_s)

# app_root designates the path of application startup file.
# app_root is different for each of the applications cli, admin, api etc.,
# app config, logging etc., would be relative to app_root
#$app_root = File.dirname(__FILE__).expand_path
$app_root = Pathname(__FILE__).realpath.dirname.to_s

puts "running with $app_root #{$app_root}"

require 'rubygems' if RUBY_VERSION < '1.9'
require 'main/cli'



exit ProjectHanlon::CLI.new.run(*ARGV)
